// Generated by rosidl_generator_cs from human_navigation_msgs/msg/HumanNaviObjectInfo.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace human_navigation_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class HumanNaviObjectInfo : RosMessage
			{
				public string name;
				public UnityEngine.Vector3 position;
				public UnityEngine.Quaternion orientation;


				public HumanNaviObjectInfo()
				{
					this.name = "";
					this.position = new UnityEngine.Vector3();
					this.orientation = new UnityEngine.Quaternion();
				}

				public HumanNaviObjectInfo(string name, UnityEngine.Vector3 position, UnityEngine.Quaternion orientation)
				{
					this.name = name;
					this.position = position;
					this.orientation = orientation;
				}

				new public static string GetMessageType()
				{
					return "human_navigation_msgs/msg/HumanNaviObjectInfo";
				}

			} // class HumanNaviObjectInfo
		} // namespace msg
	} // namespace human_navigation_msgs
} // namespace SIGVerse.RosBridge
