// Generated by rosidl_generator_cs from human_navigation_msgs/msg/HumanNaviTaskInfo.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.human_navigation_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace human_navigation_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class HumanNaviTaskInfo : RosMessage
			{
				public string environment_id;
				public human_navigation_msgs.msg.HumanNaviObjectInfo target_object;
				public human_navigation_msgs.msg.HumanNaviDestination destination;
				public System.Collections.Generic.List<human_navigation_msgs.msg.HumanNaviObjectInfo>  non_target_objects;
				public System.Collections.Generic.List<human_navigation_msgs.msg.HumanNaviObjectInfo>  furniture;


				public HumanNaviTaskInfo()
				{
					this.environment_id = "";
					this.target_object = new human_navigation_msgs.msg.HumanNaviObjectInfo();
					this.destination = new human_navigation_msgs.msg.HumanNaviDestination();
					this.non_target_objects = new System.Collections.Generic.List<human_navigation_msgs.msg.HumanNaviObjectInfo>();
					this.furniture = new System.Collections.Generic.List<human_navigation_msgs.msg.HumanNaviObjectInfo>();
				}

				public HumanNaviTaskInfo(string environment_id, human_navigation_msgs.msg.HumanNaviObjectInfo target_object, human_navigation_msgs.msg.HumanNaviDestination destination, System.Collections.Generic.List<human_navigation_msgs.msg.HumanNaviObjectInfo>  non_target_objects, System.Collections.Generic.List<human_navigation_msgs.msg.HumanNaviObjectInfo>  furniture)
				{
					this.environment_id = environment_id;
					this.target_object = target_object;
					this.destination = destination;
					this.non_target_objects = non_target_objects;
					this.furniture = furniture;
				}

				new public static string GetMessageType()
				{
					return "human_navigation_msgs/msg/HumanNaviTaskInfo";
				}

			} // class HumanNaviTaskInfo
		} // namespace msg
	} // namespace human_navigation_msgs
} // namespace SIGVerse.RosBridge
