// Generated by rosidl_generator_cs from human_navigation_msgs/msg/HumanNaviObjectStatus.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.human_navigation_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace human_navigation_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class HumanNaviObjectStatus : RosMessage
			{
				public human_navigation_msgs.msg.HumanNaviObjectInfo target_object;
				public System.Collections.Generic.List<human_navigation_msgs.msg.HumanNaviObjectInfo>  non_target_objects;


				public HumanNaviObjectStatus()
				{
					this.target_object = new human_navigation_msgs.msg.HumanNaviObjectInfo();
					this.non_target_objects = new System.Collections.Generic.List<human_navigation_msgs.msg.HumanNaviObjectInfo>();
				}

				public HumanNaviObjectStatus(human_navigation_msgs.msg.HumanNaviObjectInfo target_object, System.Collections.Generic.List<human_navigation_msgs.msg.HumanNaviObjectInfo>  non_target_objects)
				{
					this.target_object = target_object;
					this.non_target_objects = non_target_objects;
				}

				new public static string GetMessageType()
				{
					return "human_navigation_msgs/msg/HumanNaviObjectStatus";
				}

			} // class HumanNaviObjectStatus
		} // namespace msg
	} // namespace human_navigation_msgs
} // namespace SIGVerse.RosBridge
