// Generated by rosidl_generator_cs from human_navigation_msgs/msg/HumanNaviAvatarStatus.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace human_navigation_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class HumanNaviAvatarStatus : RosMessage
			{
				public geometry_msgs.msg.Pose head;
				public geometry_msgs.msg.Pose body;
				public geometry_msgs.msg.Pose left_hand;
				public geometry_msgs.msg.Pose right_hand;
				public string object_in_left_hand;
				public string object_in_right_hand;
				public bool is_target_object_in_left_hand;
				public bool is_target_object_in_right_hand;


				public HumanNaviAvatarStatus()
				{
					this.head = new geometry_msgs.msg.Pose();
					this.body = new geometry_msgs.msg.Pose();
					this.left_hand = new geometry_msgs.msg.Pose();
					this.right_hand = new geometry_msgs.msg.Pose();
					this.object_in_left_hand = "";
					this.object_in_right_hand = "";
					this.is_target_object_in_left_hand = false;
					this.is_target_object_in_right_hand = false;
				}

				public HumanNaviAvatarStatus(geometry_msgs.msg.Pose head, geometry_msgs.msg.Pose body, geometry_msgs.msg.Pose left_hand, geometry_msgs.msg.Pose right_hand, string object_in_left_hand, string object_in_right_hand, bool is_target_object_in_left_hand, bool is_target_object_in_right_hand)
				{
					this.head = head;
					this.body = body;
					this.left_hand = left_hand;
					this.right_hand = right_hand;
					this.object_in_left_hand = object_in_left_hand;
					this.object_in_right_hand = object_in_right_hand;
					this.is_target_object_in_left_hand = is_target_object_in_left_hand;
					this.is_target_object_in_right_hand = is_target_object_in_right_hand;
				}

				new public static string GetMessageType()
				{
					return "human_navigation_msgs/msg/HumanNaviAvatarStatus";
				}

			} // class HumanNaviAvatarStatus
		} // namespace msg
	} // namespace human_navigation_msgs
} // namespace SIGVerse.RosBridge
