// Generated by rosidl_generator_cs from human_navigation_msgs/msg/HumanNaviDestination.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

using SIGVerse.RosBridge.geometry_msgs.msg;

namespace SIGVerse.RosBridge 
{
	namespace human_navigation_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class HumanNaviDestination : RosMessage
			{
				public UnityEngine.Vector3 position;
				public UnityEngine.Quaternion orientation;
				public UnityEngine.Vector3 size;


				public HumanNaviDestination()
				{
					this.position = new UnityEngine.Vector3();
					this.orientation = new UnityEngine.Quaternion();
					this.size = new UnityEngine.Vector3();
				}

				public HumanNaviDestination(UnityEngine.Vector3 position, UnityEngine.Quaternion orientation, UnityEngine.Vector3 size)
				{
					this.position = position;
					this.orientation = orientation;
					this.size = size;
				}

				new public static string GetMessageType()
				{
					return "human_navigation_msgs/msg/HumanNaviDestination";
				}

			} // class HumanNaviDestination
		} // namespace msg
	} // namespace human_navigation_msgs
} // namespace SIGVerse.RosBridge
