// Generated by rosidl_generator_cs from human_navigation_msgs/msg/HumanNaviMsg.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace human_navigation_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class HumanNaviMsg : RosMessage
			{
				public string message;
				public string detail;


				public HumanNaviMsg()
				{
					this.message = "";
					this.detail = "";
				}

				public HumanNaviMsg(string message, string detail)
				{
					this.message = message;
					this.detail = detail;
				}

				new public static string GetMessageType()
				{
					return "human_navigation_msgs/msg/HumanNaviMsg";
				}

			} // class HumanNaviMsg
		} // namespace msg
	} // namespace human_navigation_msgs
} // namespace SIGVerse.RosBridge
